name: gact_plugin
description: A flutter plugin that exposes the Google/Apple Bluetooth contact tracing API.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.covidtrace.gact_plugin
    pluginClass: GactPlugin
