name: gact_plugin
description: A flutter plugin that exposes the Google/Apple Exposure Notification API.
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf:
  protoc_plugin:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.covidtrace.gact_plugin
    pluginClass: GactPlugin
